# Generated by Django 5.2.4 on 2025-07-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='call_to_action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
