# Generated by Django 5.2.4 on 2025-07-04 00:56

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_call_to_action_homepage_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='call_to_action',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('image_and_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_link',
            field=models.URLField(blank=True),
        ),
    ]
