# Generated by Django 5.2.4 on 2025-07-04 01:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_call_to_action_homepage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('image_and_text', 2), ('cta', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text on the button', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link the button should go to', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('button_text', 3), ('button_url', 4)]], {})}),
        ),
    ]
